import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import authOptions from "./api/auth/[...nextauth]/option";
import Layout from "@/components/Layout";
import SessionAccProvider from "@/context/client-provider";
import { NotificationProvider } from "@/context/NotificationContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CrazyDynamite",
  description: "Generated by Krakatua",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <SessionAccProvider session={session}>
        <NotificationProvider>
          <body className={inter.className}>
            <Layout>{children}</Layout>
          </body>
        </NotificationProvider>
      </SessionAccProvider>
    </html>
  );
}
